future: true
permalink: /:title/
url: http://Boycel_Lee.github.io
name: Boyce-Lee
author: Boyce-Lee
qq: 1772729359
email: 1772729359@qq.com

duoshuo: 李海航
beian: 
cnzz: 
weibo: 
github: Boyce-Lee.github.io
about: "这里是Boyce-Lee 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
